Repository pulumi/pulumi-vsphere, pull requests merged in 2019-06, with the labels that each got.

#26 Manage CHANGELOG with chg(1)
  CHANGELOG.md
Labels: enhancement

#27 Update pulumi-terraform to 7ace3e9b5f
  CHANGELOG.md
  go.mod
  go.sum
  sdk/nodejs/computeCluster.ts
  sdk/nodejs/computeClusterHostGroup.ts
  sdk/nodejs/computeClusterVmAffinityRule.ts
  sdk/nodejs/computeClusterVmAntiAffinityRule.ts
  sdk/nodejs/computeClusterVmDependencyRule.ts
  sdk/nodejs/computeClusterVmGroup.ts
  sdk/nodejs/computeClusterVmHostRule.ts
  sdk/nodejs/customAttribute.ts
  sdk/nodejs/datacenter.ts
  sdk/nodejs/datastoreCluster.ts
  sdk/nodejs/datastoreClusterVmAntiAffinityRule.ts
  sdk/nodejs/distributedPortGroup.ts
  sdk/nodejs/distributedVirtualSwitch.ts
  sdk/nodejs/dpmHostOverride.ts
  sdk/nodejs/drsVmOverride.ts
  sdk/nodejs/file.ts
  sdk/nodejs/folder.ts
  sdk/nodejs/haVmOverride.ts
  sdk/nodejs/hostPortGroup.ts
  sdk/nodejs/hostVirtualSwitch.ts
  sdk/nodejs/license.ts
  sdk/nodejs/nasDatastore.ts
  sdk/nodejs/provider.ts
  sdk/nodejs/resourcePool.ts
  sdk/nodejs/storageDrsVmOverride.ts
  sdk/nodejs/tag.ts
  sdk/nodejs/tagCategory.ts
  sdk/nodejs/vappContainer.ts
  sdk/nodejs/vappEntity.ts
  sdk/nodejs/virtualDisk.ts
  sdk/nodejs/virtualMachine.ts
  sdk/nodejs/virtualMachineSnapshot.ts
  sdk/nodejs/vmfsDatastore.ts
Labels: area/providers

#28 Upgrade to Terraform provider v1.12.0
  CHANGELOG.md
  go.mod
  go.sum
  sdk/go/vsphere/config/config.go
  sdk/nodejs/config/vars.ts
  sdk/nodejs/provider.ts
  sdk/python/pulumi_vsphere/config/vars.py
  sdk/python/pulumi_vsphere/provider.py
  sdk/python/pulumi_vsphere/tables.py
Labels: enhancement

#29 Update pulumi-terraform to 3635bed3a5
  go.mod
  go.sum
Labels: area/providers

#30 Update .travis.yml to scripts
  .travis.yml
Labels: area/providers, impact/no-changelog-required
